apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: resourcepp
  namespace: resourcelatency
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: resourcelatency
  placement:
      clusterAffinity: 
         clustername:
           member1
         
    
